version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - './.docker/psql/data:/var/lib/postgresql/data'
      - './.docker/psql/dump:/home/dump'
